"""Generate only the short report's main table and example assets."""
import csv
import json
import textwrap
from collections import deque
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "paper" / "sections"


def build_tables():
    source = ROOT / "analysis/out/main.csv"
    with source.open(encoding="utf-8") as f:
        records = list(csv.DictReader(f))
    if records and "Model" in records[0]:
        records = [{"player": r["Model"], "condition": "map" if r["Input"] == "map only" else "everything",
                    "n": r["Games"], "won_mean": r["Won rate"], "won_lo": r["Won rate low"],
                    "won_hi": r["Won rate high"], "progress_mean": r["Progress"], "spl_mean": r["SPL"]}
                   for r in records]
    rows = {(r["player"], r["condition"]): r for r in records}
    def won(r):
        return f"{100*float(r['won_mean']):.0f}% [{100*float(r['won_lo']):.0f}, {100*float(r['won_hi']):.0f}]"
    def efficiency(r):
        return f"{float(r['progress_mean']):.3f} / {float(r['spl_mean']):.3f}"
    lines = ["// src: analysis/out/main.md; generated by paper/build_appendices.py",
             '#figure(table(columns: (1.1fr, 1fr, 1fr, 1fr, 1fr), stroke: none, inset: 3pt,',
             'table.header([Model/baseline], [Map: won [95% CI]], [Full: won [95% CI]], [Map: progress / SPL], [Full: progress / SPL]),']
    for player in ["Solver", "Greedy (walls)", "Greedy", "Random", "Jev", "Laya", "GLiClass", "Gemma 4 26B", "Qwen3.5 4B", "DeepSeek V4.1 Flash", "DeepSeek V4.1 Flash (reasoning)"]:
        a, b = rows[(player, "map")], rows.get((player, "everything"))
        lines.append(', '.join(f'[{x}]' for x in [player, won(a), won(b) if b else '---', efficiency(a), efficiency(b) if b else '---'])+',')
    coverage = "; ".join(f"{r['player']} {r['condition']} n={r['n']}" for r in records
                         if r['condition'] in ("map", "everything") and int(r['n']) != 100)
    note = "n=100 per available model/input" + (" except " + coverage if coverage else "")
    lines.append('), caption: [Compass completion and efficiency: Compass games: '+note+'. Won-rate intervals resample puzzles; baselines use the map alone. Full means full context.], placement: top) <tab:main>')
    (OUT / 'main_table.typ').write_text('\n'.join(lines)+'\n', encoding='utf-8')


def build_example():
    request = json.loads((ROOT / 'examples/everything.json').read_text(encoding='utf-8'))
    q = request['questions']['move']
    chunks = ['state:', request['state'], '', 'model: '+request['model'], 'questions.move.type: '+q['type'],
              'questions.move.instructions: '+q['instructions'], 'questions.move.criteria:']
    chunks += [f'  {k}: {v}' for k,v in q['criteria'].items()]
    content = '\n'.join(textwrap.fill(line, width=88, replace_whitespace=False, drop_whitespace=False)
                        if len(line)>88 else line for chunk in chunks for line in chunk.split('\n'))
    (OUT/'example_request.typ').write_text('// src: examples/everything.json; complete fields, wrapped for display\n'
        + '#show raw: set text(size: 9pt)\n#set par(leading: 0.2em)\n#raw('
        + json.dumps(content) + ', block: true, lang: "text")\n', encoding='utf-8')
    state = request['state']
    board = [line.split()[1] for line in state.splitlines() if len(line.split())==2 and line.split()[0].isdigit()]
    start=(7,1,False)
    queue=deque([(start,[])])
    seen={start}
    directions=[('south',0,1),('west',-1,0),('north',0,-1),('east',1,0)]
    while queue:
        (x,y,key),path=queue.popleft()
        if board[y][x]=='G':
            route=path
            break
        for name,dx,dy in directions:
            nx,ny=x+dx,y+dy
            cell=board[ny][nx]
            if cell=='#' or cell=='D' and not key:
                continue
            target=(nx,ny,key or cell=='K')
            if target not in seen:
                seen.add(target)
                queue.append((target,path+[(name,nx,ny)]))
    assert len(route)==9
    overlay=[list(row) for row in board]
    for _,x,y in route:
        if overlay[y][x]=='.': overlay[y][x]='*'
    overlay[1][8]='X'
    drawn='   0123456789\n'+'\n'.join(f'{y:2} '+''.join(row) for y,row in enumerate(overlay))
    figure = '// src: examples/everything.json; shortest route checked by BFS in paper/build_appendices.py\n'
    figure += '#figure(block(breakable: false, grid(columns: (auto, 1fr), gutter: 12pt,\n'
    figure += 'raw('+json.dumps(drawn)+', block: true),\n'
    figure += '[*Map alone:* position (7, 1), empty inventory, map and object coordinates; "What is the best next move?"\\\n'
    figure += '*Simulated outcomes:* "move south (down): you move to (7, 2) and pick up the key".\\\n'
    figure += 'Shortest route: '+', '.join(name for name,_,_ in route)+'.])),\n'
    figure += 'kind: image, supplement: [Figure], caption: [The frozen example position. Stars trace one shortest route through K and D to G; X marks east, a suboptimal move toward open floor. Stars and X replace floor only in this figure. Appendix A gives its full-context request.]) <fig:example>\n'
    (OUT/'example_figure.typ').write_text(figure,encoding='utf-8')


if __name__ == "__main__":
    build_tables()
    build_example()
    from sync_results import sync_results
    sync_results()
    print("Generated the compact main table, complete example request and checked nine-step example route.")
